### ISSUE TITLE
Remove convos.conf

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#47]
We want to skip using the config file. The plan is to move the parameters to %ENV or redis:
- [ ] ~~name: Should be set by the first user that register~~ See #99
- [x] redis: Default to redis://127.0.0.1:6379/1, but use %ENV if possible. The keys should match the default keys on heroku and dotcloud. #47
- [x] secret: We should generate the secrets and store them in Redis #47
- [x] invite_code: Should be set by the first user that register #84
- [x] hypnotoad: Add support for MOJO_LISTEN, #100
- [x] backend - embedded: $ENV{CONVOS_BACKEND_EMBEDDED} // 1
