### ISSUE TITLE
Placeholder for things to decide

### ISSUE THREAD

**Issue by jhthorsen** [convos-chat/convos#77]
I want to do some changes:
- [x] I want to remove the "go to bottom" button or at least reformat it. #97
- [x] Want timestamp on every messages from today. #96 
- [x] Figure out why autocomplete doesn't take the last nick that said something. #97
- [x] Make view.network route accept POST so we can send data without websocket
- [ ] Get rid of data-target and data-network. Thinking about data-path="/:network/:target" instead.
- [ ] Move to react.js

Need to discuss this with @marcusramberg before changing.
